<?xml version="1.0"?>
<!DOCTYPE Collections [
    <!ELEMENT Collections (collection)*>
    <!ELEMENT collection (methods)>
        <!ATTLIST collection id ID #IMPLIED>
    <!ELEMENT methods (method)*>
    <!ELEMENT method (type, value, params)>
    <!ELEMENT type (#PCDATA)>
    <!ELEMENT value (#PCDATA)>
    <!ELEMENT params (paramsValue)*>
    <!ELEMENT paramsValue (#PCDATA)>
]>
<Collections>
    <collection id="ArrayList">
        <methods>
            <method>
                <type>Access</type>
                <value>get</value>
                <params>
                    <paramsValue>java.lang.Integer</paramsValue>
                </params>
            </method>
            <method>
                <type>Search</type>
                <value>contains</value>
                <params>
                    <paramsValue>java.lang.Object</paramsValue>
                </params>
            </method>
            <method>
                <type>Insertion</type>
                <value>add</value>
                <params>
                    <paramsValue>java.lang.Object</paramsValue>
                </params>
            </method>
            <method>
                <type>Removal</type>
                <value>remove</value>
                <params>
                    <paramsValue>java.lang.Object</paramsValue>
                </params>
            </method>
            <method>
                <type>size</type>
                <value>size</value>
                <params>
                </params>
            </method>
        </methods>
    </collection>
    <collection id="LinkedList">
        <methods>
            <method>
                <type>Access</type>
                <value>get</value>
                <params>
                    <paramsValue>java.lang.Integer</paramsValue>
                </params>
            </method>
            <method>
                <type>Search</type>
                <value>contains</value>
                <params>
                    <paramsValue>java.lang.Object</paramsValue>
                </params>
            </method>
            <method>
                <type>Insertion</type>
                <value>add</value>
                <params>
                    <paramsValue>java.lang.Object</paramsValue>
                </params>
            </method>
            <method>
                <type>Removal</type>
                <value>remove</value>
                <params>
                    <paramsValue>java.lang.Object</paramsValue>
                </params>
            </method>
        </methods>
    </collection>
    <collection id="ArrayDeque">
        <methods>
            <method>
                <type>Access</type>
                <value>peek</value>
                <params>
                </params>
            </method>
            <method>
                <type>Search</type>
                <value>contains</value>
                <params>
                    <paramsValue>java.lang.Object</paramsValue>
                </params>
            </method>
            <method>
                <type>Insertion</type>
                <value>offer</value>
                <params>
                    <paramsValue>java.lang.Object</paramsValue>
                </params>
            </method>
            <method>
                <type>Removal</type>
                <value>remove</value>
                <params>
                    <paramsValue>java.lang.Object</paramsValue>
                </params>
            </method>
        </methods>
    </collection>
    <collection id="PriorityQueue">
        <methods>
            <method>
                <type>Access</type>
                <value>peek</value>
                <params>
                </params>
            </method>
            <method>
                <type>Search</type>
                <value>contains</value>
                <params>
                    <paramsValue>java.lang.Object</paramsValue>
                </params>
            </method>
            <method>
                <type>Insertion</type>
                <value>offer</value>
                <params>
                    <paramsValue>java.lang.Object</paramsValue>
                </params>
            </method>
            <method>
                <type>Removal</type>
                <value>remove</value>
                <params>
                    <paramsValue>java.lang.Object</paramsValue>
                </params>
            </method>
        </methods>
    </collection>
    <collection id="HashSet">
        <methods>
            <method>
                <type>Search</type>
                <value>contains</value>
                <params>
                    <paramsValue>java.lang.Object</paramsValue>
                </params>
            </method>
            <method>
                <type>Insertion</type>
                <value>add</value>
                <params>
                    <paramsValue>java.lang.Object</paramsValue>
                </params>
            </method>
            <method>
                <type>Removal</type>
                <value>remove</value>
                <params>
                    <paramsValue>java.lang.Object</paramsValue>
                </params>
            </method>
        </methods>
    </collection>
    <collection id="TreeSet">
        <methods>
            <method>
                <type>Search</type>
                <value>contains</value>
                <params>
                    <paramsValue>java.lang.Object</paramsValue>
                </params>
            </method>
            <method>
                <type>Insertion</type>
                <value>add</value>
                <params>
                    <paramsValue>java.lang.Object</paramsValue>
                </params>
            </method>
            <method>
                <type>Removal</type>
                <value>remove</value>
                <params>
                    <paramsValue>java.lang.Object</paramsValue>
                </params>
            </method>
        </methods>
    </collection>
    <collection id="HashMap">
        <methods>
            <method>
                <type>Access</type>
                <value>get</value>
                <params>
                    <paramsValue>java.lang.Object</paramsValue>
                </params>
            </method>
            <method>
                <type>Search</type>
                <value>containsKey</value>
                <params>
                    <paramsValue>java.lang.Object</paramsValue>
                </params>
            </method>
            <method>
                <type>Insertion</type>
                <value>put</value>
                <params>
                    <paramsValue>java.lang.Object</paramsValue>
                    <paramsValue>java.lang.Object</paramsValue>
                </params>
            </method>
            <method>
                <type>Removal</type>
                <value>remove</value>
                <params>
                    <paramsValue>java.lang.Object</paramsValue>
                </params>
            </method>
        </methods>
    </collection>
    <collection id="TreeMap">
        <methods>
            <method>
                <type>Access</type>
                <value>get</value>
                <params>
                    <paramsValue>java.lang.Object</paramsValue>
                </params>
            </method>
            <method>
                <type>Search</type>
                <value>containsKey</value>
                <params>
                    <paramsValue>java.lang.Object</paramsValue>
                </params>
            </method>
            <method>
                <type>Insertion</type>
                <value>put</value>
                <params>
                    <paramsValue>java.lang.Object</paramsValue>
                    <paramsValue>java.lang.Object</paramsValue>
                </params>
            </method>
            <method>
                <type>Removal</type>
                <value>remove</value>
                <params>
                    <paramsValue>java.lang.Object</paramsValue>
                </params>
            </method>
        </methods>
    </collection>
</Collections>